import { describe, expect, it } from "vitest";

import { resolvePetAnimation } from "../domain/pet-package";
import { toLoadedImportedPetPackage } from "./pet-package-store";

const manifest = {
  schemaVersion: 1,
  id: "local-test",
  name: "Local Test",
  version: "1.0.0",
  author: "Test",
  license: "Test-only",
  canvas: { width: 128, height: 128, fit: "contain", anchor: { x: 0.5, y: 1 } },
  animations: {
    idle: { source: "animations/idle.gif", mediaType: "image/gif", loop: true, alt: "idle" },
  },
  states: {
    idle: "idle",
    thinking: "idle",
    planning: "idle",
    coding: "idle",
    testing: "idle",
    success: "idle",
    error: "idle",
  },
  fallbackAnimation: "idle",
};

describe("imported pet package records", () => {
  it("converts each copied Windows path instead of resolving against encoded backslashes", () => {
    const loaded = toLoadedImportedPetPackage(
      {
        catalogId: `local-${"a".repeat(24)}`,
        manifestPath: "C:\\app-data\\pet-packages\\local-a\\pet.json",
        assetPaths: {
          "animations/idle.gif":
            "C:\\app-data\\pet-packages\\local-a\\animations\\idle.gif",
        },
        manifest,
      },
      (path) => `http://asset.localhost/${encodeURIComponent(path)}`,
    );

    expect(loaded.catalogId).toBe(`local-${"a".repeat(24)}`);
    expect(loaded.source).toBe("imported");
    expect(loaded.manifestUrl.href).toBe(
      "http://asset.localhost/C%3A%5Capp-data%5Cpet-packages%5Clocal-a%5Cpet.json",
    );
    expect(resolvePetAnimation(loaded, "idle").url).toBe(
      "http://asset.localhost/C%3A%5Capp-data%5Cpet-packages%5Clocal-a%5Canimations%5Cidle.gif",
    );
  });

  it("requires an exact copied path for every declared asset", () => {
    expect(() =>
      toLoadedImportedPetPackage(
        {
          catalogId: `local-${"a".repeat(24)}`,
          manifestPath: "C:\\app-data\\pet.json",
          assetPaths: {},
          manifest,
        },
        (path) => `http://asset.localhost/${encodeURIComponent(path)}`,
      ),
    ).toThrow(/do not match/);
  });

  it("converts package-provided reduced-motion targets through the same scoped asset map", () => {
    const loaded = toLoadedImportedPetPackage(
      {
        catalogId: `local-${"b".repeat(24)}`,
        manifestPath: "C:\\app-data\\pet-packages\\local-b\\pet.json",
        assetPaths: {
          "animations/idle.gif":
            "C:\\app-data\\pet-packages\\local-b\\animations\\idle.gif",
          "animations/idle-static.png":
            "C:\\app-data\\pet-packages\\local-b\\animations\\idle-static.png",
        },
        manifest: {
          ...manifest,
          animations: {
            ...manifest.animations,
            "idle-static": {
              source: "animations/idle-static.png",
              mediaType: "image/png",
              loop: false,
              alt: "idle static",
            },
          },
          reducedMotionAnimations: { idle: "idle-static" },
        },
      },
      (path) => `http://asset.localhost/${encodeURIComponent(path)}`,
    );

    expect(loaded.manifest.reducedMotionAnimations).toEqual({ idle: "idle-static" });
    expect(loaded.assetUrls?.["animations/idle-static.png"]).toContain(
      "animations%5Cidle-static.png",
    );
  });

  it("rejects records whose opaque id is not generated by the importer", () => {
    expect(() =>
      toLoadedImportedPetPackage(
        { catalogId: "../../escape", manifestPath: "ignored", manifest },
        () => "http://asset.localhost/pet.json",
      ),
    ).toThrow(/id is invalid/);
  });
});
